# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b2de81cf87e755006a9354a5ed97a0263a81c90e73ebe6e3d3f1c5f200dde7cf5b90f8bace85d9777bce8af00fce20ea7e24c5dcd54e3709d6661929c6684f6

test:
  secret_key_base: 4eb74907fcdbee19724610e895d3701e485e7311d2b9a00b9cef9a8cc08f1cf883a3307fef9db4c8b1d6474bc51024538d8eeefae2420540b65e237348865cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
